name: "Workflow example"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 5,17 * * *'

jobs:
  python-job:
    name: "Python job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
#     If you need to install extra packages
#     - name: Install dependencies
#       run: pip install -r requirements.txt
      - name: Run python script
        run: python job.py
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt
