name: "Workflow example"
on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  hello:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "Hello from GitHub Actions!"
