name: "Workflow example"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '57 05 * * *'

jobs:
  python-job:
    name: "Python job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - name: Run python script
        run: echo Hello World
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt
